plugins {
    id 'org.springframework.boot' version '3.5.13'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java-library'
}

allprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'

    ext {
        set('springBootVersion', "3.5.13")
        set('springCloudVersion', "2025.0.2")
        set('mybatisPlusBootVersion', "3.5.16")
        set('mybatisPlusGeneratorVersion', "3.5.16")
        set('hutoolVersion', "5.8.34")
        set('knife4jVersion', "4.5.0")
        set('springdocVersion', "2.8.13")
        set('dom4jVersion', "2.1.4")
        set('slf4jApiVersion', "2.0.16")
        set('dysmsapiVersion', "2.0.24")
        set('lombokVersion', "1.18.44")
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-autoconfigure'
        annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
        annotationProcessor 'org.projectlombok:lombok'
        compileOnly 'org.projectlombok:lombok'
        implementation "cn.hutool:hutool-all"
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
        imports {
            mavenBom "com.github.xiaoymin:knife4j-dependencies:${knife4jVersion}"
        }
        dependencies {
            dependency "com.baomidou:mybatis-plus-spring-boot3-starter:${mybatisPlusBootVersion}"
            dependency "com.baomidou:mybatis-plus-jsqlparser:${mybatisPlusBootVersion}"
            dependency "com.baomidou:mybatis-plus-generator:${mybatisPlusGeneratorVersion}"
            dependency "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"
            dependency "org.projectlombok:lombok:${lombokVersion}"
            dependency "cn.hutool:hutool-all:${hutoolVersion}"
            dependency "org.dom4j:dom4j:${dom4jVersion}"
            dependency "org.slf4j:slf4j-api:${slf4jApiVersion}"
            dependency "com.aliyun:dysmsapi20170525:${dysmsapiVersion}"
        }
    }

    sourceSets {
        main {
            resources {
                srcDirs = ['src/main/resources', 'src/main/java']
                includes = ['**/*.xml', '**/*.properties', '**/*.yml', '**/*.yaml']
            }
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

//    jar {
//        enabled = true
//        archiveClassifier = ''
//    }

//    task javadocJar(type: Jar) {
//        from javadoc
//        classifier = 'javadoc'
//    }
}
